### ISSUE TITLE
error - ST7735-MoodeCoverArt.py

### ISSUE THREAD

**Issue by nadim24** [rusconi/ST7735-MoodeCoverArt#1]
Prompt the correct connection to the GPIO - SPI of the ST7735 display. I can't connect. 
LED - 13 gpio
SCK - 11
SDA - 10
A0   - 24
RST - 22
CS   - 0
GND - gnd
VIN  - 3,3v
Installed the script. https://github.com/rusconi/ST7735-MoodeCoverArt
When testing, it gives an error.
Test the script:
python3 /home/pi/ST7735-MoodeCoverArt.py
error screen: https://prnt.sc/whjjao
Thank you.

**Comment by rusconi** [comment]
Apologies. I had left some testing code in. This has now been removed and the Permission denied error should not happen again.

I have added an image of how my TFT7735 is connected to the Raspberry Pi in the Readme.

Hope this is helpful

**Comment by nadim24** [comment]
The display does not display the picture correctly
https://prnt.sc/wi8j6t
